### ISSUE TITLE
Don't use timebased versioncodes

### ISSUE THREAD

**Issue by ghost** [franciscofranco/Simple-Reboot-app#3]
Timebased versioncodes, at least autogenerated once, break reproducible builds. I would expect that checking out a git commit hash would always give me the same version. Instead, I now get a newer version which every build. Imaging you want to build the current version and an older release. Depending on when you build which, an older version might be proposed as update, since it has a newer timestamp.

If you really want timebased vercodes, maybe get the time from the git commit instead?

**Comment by franciscofranco** [comment]
I see what you mean. This works for my setup and I don't have to worry about changing the versionCode anymore. You can make a pull request if you have a better working alternative ;)
