### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by ghost** [franciscofranco/Simple-Reboot-app#6]
Would you be able to re-put the descriptions? 

Especially for first-time users..

**Comment by mikhoul** [comment]
Especially Soft-reboot I'm not sure what it does, it seem to reboot but what is the difference between other reboot.

p.s.: I'm new on Android too.

Regards :octocat:

**Comment by franciscofranco** [comment]
It just reboots Android, not the entire phone.

**Comment by mikhoul** [comment]
A small request @franciscofranco I use the app on an Android TV-Box so I use mainly the remote (without cursor) to control the interface, so when I see the interface SimpleReboot I'm not able to navigate the option and press OK with the remote I need to enable the cursor of the Air mouse.

So if it is easy to do just change the Interface to be able to navigate it with a  the remote buttons  for non-touch device like TV-Box. 

Regards :octocat:
